wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.33
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      4: 3.7.7
      5: 0.10.33
      8:
      - 5
activation:
  desc: null
  value: lrelu
b1:
  desc: null
  value: 0.5
b2:
  desc: null
  value: 0.999
baseroot:
  desc: null
  value: C:\Users\yzzha\Desktop\dataset\ILSVRC2012_val_256
batch_size:
  desc: null
  value: 4
bbox_shape:
  desc: null
  value: 120
checkpoint_interval:
  desc: null
  value: 1
cudnn_benchmark:
  desc: null
  value: true
data_dir:
  desc: null
  value: ../dataset
epochs:
  desc: null
  value: 200
gan_type:
  desc: null
  value: WGAN
gpu_ids:
  desc: null
  value: 2, 3
image_height:
  desc: null
  value: 513
image_width:
  desc: null
  value: 431
in_channels:
  desc: null
  value: 2
init_gain:
  desc: null
  value: 0.02
init_type:
  desc: null
  value: xavier
input_length:
  desc: null
  value: 220500
lambda_gan:
  desc: null
  value: 1
lambda_l1:
  desc: null
  value: 100
lambda_perceptual:
  desc: null
  value: 10
latent_channels:
  desc: null
  value: 64
load_name:
  desc: null
  value: ''
lr_d:
  desc: null
  value: 0.0004
lr_decrease_epoch:
  desc: null
  value: 5
lr_decrease_factor:
  desc: null
  value: 0.5
lr_g:
  desc: null
  value: 0.0001
margin:
  desc: null
  value: 10
mask_type:
  desc: null
  value: time
multi_gpu:
  desc: null
  value: true
norm:
  desc: null
  value: in
num_workers:
  desc: null
  value: 8
out_channels:
  desc: null
  value: 1
pad_type:
  desc: null
  value: zero
sample_path:
  desc: null
  value: /data2/personal/jaejun/inpainting/results/210714/time/samples
save_path:
  desc: null
  value: /data2/personal/jaejun/inpainting/results/210714/time/models
weight_decay:
  desc: null
  value: 0
